In [3]:
from dotenv import load_dotenv
import os
import boto3
import pandas as pd

load_dotenv()

s3 = boto3.client(
    "s3",
    endpoint_url=f"https://{os.environ['R2_ACCOUNT_ID']}.r2.cloudflarestorage.com",
    aws_access_key_id=os.environ["R2_ACCESS_KEY_ID"],
    aws_secret_access_key=os.environ["R2_SECRET_ACCESS_KEY"],
    region_name="auto",
)

bucket = "colombia-dengue-forecasting"

In [6]:
years = ["2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025"]

cases_data_frames = []

for year in years:
    key = f"raw/cases/Datos_{year}_210.xlsx"
    local_path = f"data/raw/cases/{year}.xlsx"

    s3.download_file(bucket, key, local_path)
    df = pd.read_excel(local_path)
    cases_data_frames.append(df)

In [ ]:
cases_data_frames[0].info()

<class 'pandas.DataFrame'>
RangeIndex: 100117 entries, 0 to 100116
Data columns (total 69 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   CONSECUTIVE                100117 non-null  int64
 1   COD_EVE                    100117 non-null  int64
 2   FEC_NOT                    100117 non-null  str
 3   SEMANA                     100117 non-null  int64
 4   ANO                        100117 non-null  int64
 5   COD_PRE                    100117 non-null  int64
 6   COD_SUB                    100117 non-null  int64
 7   EDAD                       100117 non-null  int64
 8   UNI_MED                    100117 non-null  int64
 9   SEXO                       100117 non-null  str
 10  COD_PAIS_O                 100117 non-null  int64
 11  COD_DPTO_O                 100117 non-null  int64
 12  COD_MUN_O                  100117 non-null  int64
 13  AREA                       100117 non-null  int64
 14  OCUPACION                  100117 non-null  int64
 15  TIP_SS                     100117 non-null  str
 16  COD_ASE                    96216 non-null   str
 17  PER_ETN                    100117 non-null  int64
 18  GRU_POB                    0 non-null       float64
 19  nom_grupo                  0 non-null       float64
 20  estrato                    0 non-null       float64
 21  GP_DISCAPA                 100117 non-null  int64
 22  GP_DESPLAZ                 100117 non-null  int64
 23  GP_MIGRANT                 100117 non-null  int64
 24  GP_CARCELA                 100117 non-null  int64
 25  GP_GESTAN                  100117 non-null  int64
 26  sem_ges                    0 non-null       float64
 27  GP_INDIGEN                 100117 non-null  int64
 28  GP_POBICFB                 100117 non-null  int64
 29  GP_MAD_COM                 100117 non-null  int64
 30  GP_DESMOVI                 100117 non-null  int64
 31  GP_PSIQUIA                 100117 non-null  int64
 32  GP_VIC_VIO                 100117 non-null  int64
 33  GP_OTROS                   100117 non-null  int64
 34  fuente                     0 non-null       float64
 35  COD_PAIS_R                 0 non-null       float64
 36  COD_DPTO_R                 100117 non-null  int64
 37  COD_MUN_R                  100117 non-null  int64
 38  COD_DPTO_N                 100117 non-null  int64
 39  COD_MUN_N                  100117 non-null  int64
 40  FEC_CON                    100093 non-null  str
 41  INI_SIN                    100093 non-null  str
 42  TIP_CAS                    100117 non-null  int64
 43  PAC_HOS                    100117 non-null  int64
 44  FEC_HOS                    29484 non-null   str
 45  CON_FIN                    100117 non-null  int64
 46  FEC_DEF                    2 non-null       str
 47  AJUSTE                     100117 non-null  int64
 48  FECHA_NTO                  99828 non-null   str
 49  CBMTE                      3 non-null       str
 50  FEC_ARC_XL                 100117 non-null  str
 51  FEC_AJU                    100117 non-null  str
 52  FM_FUERZA                  803 non-null     float64
 53  FM_UNIDAD                  803 non-null     float64
 54  FM_GRADO                   803 non-null     str
 55  confirmados                100117 non-null  int64
 56  va_sispro                  100117 non-null  int64
 57  Estado_final_de_caso       100117 non-null  int64
 58  nom_est_f_caso             100117 non-null  str
 59  Nombre_upgd                100117 non-null  str
 60  Pais_ocurrencia            100117 non-null  str
 61  Nombre_evento              100117 non-null  str
 62  Departamento_ocurrencia    100117 non-null  str
 63  Municipio_ocurrencia       100117 non-null  str
 64  Pais_residencia            0 non-null       float64
 65  Departamento_residencia    100117 non-null  str
 66  Municipio_residencia       100117 non-null  str
 67  Departamento_Notificacion  100117 non-null  str
 68  Municipio_notificacion     100117 non-null  str
dtypes: float64(9), int64(37), str(23)
memory usage: 52.7 MB

| Column | Meaning | Values / format |
|---|---|---|
| `COD_EVE` | SIVIGILA event code | `210` = dengue; `220` = severe dengue; `580` = dengue mortality, handled as a separate event |
| `ANO` | Epidemiological year | The years present in the dataset |
| `SEMANA` | Epidemiological week | Week number, generally `1`–`53`; use the week paired with `ANO` |
| `COD_DPTO_O` | Department where the case occurred | DANE DIVIPOLA department code; keep as text to preserve leading zeros |
| `COD_MUN_O` | Municipality where the case occurred | DANE DIVIPOLA municipality code; check whether this export stores the municipality component or the full code |
| `COD_PAIS_O` | Country where the case occurred | Country code; Colombia is commonly represented as `170` |
| `INI_SIN` | Date symptoms began | Date; parse using the format in your source file |
| `FEC_NOT` | Date the case was notified | Date; parse using the format in your source file |
| `TIP_CAS` | Initial case classification/type | Event- and year-specific code; check the dengue data dictionary and the values in your files |
| `AJUSTE` | Case adjustment or updated classification | Dengue protocol mentions `3` = confirmed by laboratory, `5` = confirmed by epidemiological link, `6` = discarded, and `D` = digitization error; verify other values by year |
| `CONSECUTIVE` | Sequential record identifier | Identifier, not a category; uniqueness is not guaranteed across separate yearly files |

In [ ]:
cols_to_keep = ["CONSECUTIVE", "COD_EVE", "ANO", "SEMANA", "COD_DPTO_O", "COD_MUN_O", "COD_PAIS_O", "INI_SIN", "FEC_NOT", "TIP_CAS", "AJUSTE"]
for i in range(0,len(cases_data_frames)):
    cases_data_frames[i] = cases_data_frames[i][cols_to_keep]

cases_data_frames[0].head()

,CONSECUTIVE,COD_EVE,ANO,SEMANA,COD_DPTO_O,COD_MUN_O,COD_PAIS_O,INI_SIN,FEC_NOT,TIP_CAS,AJUSTE
0,713315,210,2016,21,5,1,170,25/05/2016 12:00:00 a. m.,1/06/2016 12:00:00 a. m.,3,0
1,713316,210,2016,3,5,1,170,18/01/2016 12:00:00 a. m.,21/01/2016 12:00:00 a. m.,3,0
2,713323,210,2016,2,5,1,170,15/01/2016 12:00:00 a. m.,23/01/2016 12:00:00 a. m.,2,0
3,713353,210,2016,22,5,1,170,1/06/2016 12:00:00 a. m.,11/06/2016 12:00:00 a. m.,3,0
4,713310,210,2016,25,5,1,170,20/06/2016 12:00:00 a. m.,25/06/2016 12:00:00 a. m.,2,0

| Column | Value | Meaning |
|---|---:|---|
| `TIP_CAS` | `2` | Probable case |
| `TIP_CAS` | `3` | Confirmed by laboratory |
| `TIP_CAS` | `5` | Confirmed by epidemiological link |
| `AJUSTE` | `0` | No adjustment / first report |
| `AJUSTE` | `3` | Adjustment confirming by laboratory |
| `AJUSTE` | `5` | Adjustment confirming by epidemiological link |
| `AJUSTE` | `7` | Other update to the record; not a case classification |

In [ ]:
global_cases = pd.concat(cases_data_frames, axis=0, join='outer', ignore_index=True)

In [ ]:
# Only cases that ocurred in Colombia, identified with M49 code 170 1037761
global_cases = global_cases[global_cases['COD_PAIS_O'] == 170]
global_cases

,CONSECUTIVE,COD_EVE,ANO,SEMANA,COD_DPTO_O,COD_MUN_O,COD_PAIS_O,INI_SIN,FEC_NOT,TIP_CAS,AJUSTE
0,713315,210,2016,21,5,1,170,25/05/2016 12:00:00 a. m.,1/06/2016 12:00:00 a. m.,3,0
1,713316,210,2016,3,5,1,170,18/01/2016 12:00:00 a. m.,21/01/2016 12:00:00 a. m.,3,0
2,713323,210,2016,2,5,1,170,15/01/2016 12:00:00 a. m.,23/01/2016 12:00:00 a. m.,2,0
3,713353,210,2016,22,5,1,170,1/06/2016 12:00:00 a. m.,11/06/2016 12:00:00 a. m.,3,0
4,713310,210,2016,25,5,1,170,20/06/2016 12:00:00 a. m.,25/06/2016 12:00:00 a. m.,2,0
...,...,...,...,...,...,...,...,...,...,...,...
1040490,4754,210,2025,51,68,689,170,18/12/2025 12:00:00 a. m.,19/12/2025 12:00:00 a. m.,3,0
1040491,4716,210,2025,3,8,758,170,12/01/2025 12:00:00 a. m.,17/01/2025 12:00:00 a. m.,3,3
1040492,4655,210,2025,50,47,1,170,8/12/2025 12:00:00 a. m.,12/12/2025 12:00:00 a. m.,3,0
1040493,1974,210,2025,28,73,1,170,10/07/2025 12:00:00 a. m.,14/07/2025 12:00:00 a. m.,2,7
1040494,4757,210,2025,40,47,1,170,29/09/2025 12:00:00 a. m.,4/10/2025 12:00:00 a. m.,3,3

In [ ]:
for col in cols_to_keep:
    print(col)
    print(global_cases[col].isnull().sum())

CONSECUTIVE
0
COD_EVE
0
ANO
0
SEMANA
0
COD_DPTO_O
0
COD_MUN_O
0
COD_PAIS_O
0
INI_SIN
24
FEC_NOT
0
TIP_CAS
0
AJUSTE
0

| Código | Departamento | Código | Departamento |
|---:|---|---:|---|
| 05 | Antioquia | 52 | Nariño |
| 08 | Atlántico | 54 | Norte de Santander |
| 11 | Bogotá, D.C. | 63 | Quindío |
| 13 | Bolívar | 66 | Risaralda |
| 15 | Boyacá | 68 | Santander |
| 17 | Caldas | 70 | Sucre |
| 18 | Caquetá | 73 | Tolima |
| 19 | Cauca | 76 | Valle del Cauca |
| 20 | Cesar | 81 | Arauca |
| 23 | Córdoba | 85 | Casanare |
| 25 | Cundinamarca | 86 | Putumayo |
| 27 | Chocó | 88 | San Andrés y Providencia |
| 41 | Huila | 91 | Amazonas |
| 44 | La Guajira | 94 | Guainía |
| 47 | Magdalena | 95 | Guaviare |
| 50 | Meta | 97 | Vaupés |
|  |  | 99 | Vichada |

In [ ]:
department_codes = global_cases["COD_DPTO_O"].value_counts().index.tolist()
department_codes_df = pd.DataFrame(data=department_codes, columns=['COD_DPTO_O'])
department_codes_df = department_codes_df[department_codes_df['COD_DPTO_O'] != 0]
department_codes_df

    COD_DPTO_O
0           76
1           68
2           73
3            5
4           50
5           13
6           41
7            8
8           54
9           23
10          25
11          20
12          70
13          85
14          47
15          19
16          86
17          44
18          66
19          63
20          18
21          81
22          52
23          27
24          15
25          17
26          91
27          95
28          99
29          88
30          94
31          97

In [ ]:
global_cases = global_cases[global_cases["COD_DPTO_O"] != 0]
global_cases.shape[0]

1037727

In [ ]:
keys = ['ANO', 'SEMANA', 'COD_DPTO_O']
counts_by_week_year_department = global_cases.groupby(keys).size().rename('case_count').reset_index()
counts_by_week_year_department

        ANO  SEMANA  COD_DPTO_O  case_count
0      2016       1           5         391
1      2016       1           8         128
2      2016       1          13          69
3      2016       1          15          21
4      2016       1          17          25
...     ...     ...         ...         ...
15400  2025      53          85           6
15401  2025      53          86           9
15402  2025      53          91          12
15403  2025      53          95           4
15404  2025      53          99           3

[15405 rows x 4 columns]

In [ ]:

import numpy as np

epidemological_weeks_per_year = [(2016, 52),(2017, 52),(2018, 52),(2019, 52),(2020, 53),(2021, 52),(2022, 52),(2023, 52),(2024, 52),(2025, 53)]

year_week = np.array([(year , week) for year, num_weeks in epidemological_weeks_per_year for week in range(1, num_weeks + 1)])
year_week_df = pd.DataFrame(data = year_week, columns=['ANO', 'SEMANA'])
year_week_df

      ANO  SEMANA
0    2016       1
1    2016       2
2    2016       3
3    2016       4
4    2016       5
..    ...     ...
517  2025      49
518  2025      50
519  2025      51
520  2025      52
521  2025      53

[522 rows x 2 columns]

In [ ]:
department_year_week_df = year_week_df.merge(department_codes_df, how='cross')
department_year_week_df

        ANO  SEMANA  COD_DPTO_O
0      2016       1          76
1      2016       1          68
2      2016       1          73
3      2016       1           5
4      2016       1          50
...     ...     ...         ...
16699  2025      53          95
16700  2025      53          99
16701  2025      53          88
16702  2025      53          94
16703  2025      53          97

[16704 rows x 3 columns]

In [ ]:
weekly_cases_complete_df = department_year_week_df.merge(counts_by_week_year_department, on=keys, how='left').fillna({'case_count' : 0})
weekly_cases_complete_df['case_count'] = weekly_cases_complete_df['case_count'].astype(int)
weekly_cases_complete_df

        ANO  SEMANA  COD_DPTO_O  case_count
0      2016       1          76         558
1      2016       1          68         148
2      2016       1          73         269
3      2016       1           5         391
4      2016       1          50          57
...     ...     ...         ...         ...
16699  2025      53          95           4
16700  2025      53          99           3
16701  2025      53          88           0
16702  2025      53          94           0
16703  2025      53          97           0

[16704 rows x 4 columns]

In [ ]:
print(weekly_cases_complete_df['COD_DPTO_O'].unique())

[76 68 73  5 50 13 41  8 54 23 25 20 70 85 47 19 86 44 66 63 18 81 52 27
 15 17 91 95 99 88 94 97]

In [15]:
from zipfile import ZipFile
import xarray as xr

with ZipFile('./data/raw/2m_temperature/temp.zip') as z:
    z.extract('data.grib', './data/raw/2m_temperature')

dataset = xr.open_dataset(
    './data/raw/2m_temperature/data.grib',
    engine='cfgrib',
    chunks={'time': 24}
)

print(dataset)

Ignoring index file './data/raw/2m_temperature/data.grib.5b7b6.idx' older than GRIB file

<xarray.Dataset> Size: 2GB
Dimensions:     (time: 87672, latitude: 77, longitude: 69)
Coordinates:
  * time        (time) datetime64[ns] 701kB 2016-01-01 ... 2025-12-31T23:00:00
    valid_time  (time) datetime64[ns] 701kB dask.array<chunksize=(24,), meta=np.ndarray>
  * latitude    (latitude) float64 616B 14.0 13.75 13.5 ... -4.5 -4.75 -5.0
  * longitude   (longitude) float64 552B -83.0 -82.75 -82.5 ... -66.25 -66.0
    number      int64 8B ...
    step        timedelta64[ns] 8B ...
    surface     float64 8B ...
Data variables:
    t2m         (time, latitude, longitude) float32 2GB dask.array<chunksize=(24, 77, 69), meta=np.ndarray>
Attributes:
    GRIB_edition:            1
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-10-12T10:29 GRIB to CDM+CF via cfgrib-0.9.1...

In [ ]:
import geopandas as gpd

department_polygons = gpd.read_file('./data/map_polygons/department_polygons.geojson').to_crs('EPSG:4326')
department_polygons

,dpto_ccdgo,dpto_cnmbr,dpto_ano_c,dpto_act_a,dpto_narea,dpto_nano,shape_Leng,shape_Area,geometry
0,05,ANTIOQUIA,1886,Constitucion Politica de 1886,62806.982729,2024,21.479346,5.135102,"MULTIPOLYGON (((-76.41355 8.87383, -76.40465 8..."
1,08,ATLÁNTICO,1910,Ley 21 de 1910,3314.560851,2024,2.569609,0.273832,"MULTIPOLYGON (((-74.84946 11.09778, -74.84938 ..."
2,11,"BOGOTÁ, D.C.",1538,Constitucion Politica de 1886,1622.852979,2024,3.765371,0.132208,"MULTIPOLYGON (((-74.07059 4.82856, -74.07036 4..."
3,13,BOLÍVAR,1886,Constitucion Politica de 1886,26720.306964,2024,16.272240,2.195667,"MULTIPOLYGON (((-76.17318 9.38785, -76.17287 9..."
4,15,BOYACÁ,1886,Constitucion Politica de 1886,23137.997637,2024,15.906767,1.888387,"MULTIPOLYGON (((-72.17368 7.05308, -72.17277 7..."
5,17,CALDAS,1905,11 de Abril de 1905,7425.220161,2024,6.664502,0.605498,"MULTIPOLYGON (((-74.67154 5.77147, -74.67054 5..."
6,18,CAQUETÁ,1981,Ley 78 del 29 de Diciembre de 1981,92831.282595,2024,21.218640,7.540241,"MULTIPOLYGON (((-76.09066 1.07012, -76.09066 1..."
7,19,CAUCA,1857,15 de junio de 1857,31242.864721,2024,13.953178,2.534415,"MULTIPOLYGON (((-76.45922 3.32872, -76.45878 3..."
8,20,CESAR,1967,Ley 25 21 de junio de 1967,22534.251126,2024,12.748366,1.855656,"MULTIPOLYGON (((-73.45335 10.86765, -73.45318 ..."
9,23,CÓRDOBA,1951,Ley 9 del 18 de Diciembre de 1951,25086.239945,2024,9.711373,2.057508,"MULTIPOLYGON (((-75.88119 9.42363, -75.8794 9...."
10,25,CUNDINAMARCA,1886,Constitucion Politica de 1886,22370.655342,2024,13.121765,1.823645,"MULTIPOLYGON (((-74.32755 5.82396, -74.32716 5..."
11,27,CHOCÓ,1947,Ley 13 del 3 de Noviembre de 1947,48354.730215,2024,20.631028,3.939867,"MULTIPOLYGON (((-77.36996 6.34839, -77.36997 6..."
12,41,HUILA,1905,Ley 46 de 1905,18141.660549,2024,10.335565,1.474219,"MULTIPOLYGON (((-74.51853 3.836, -74.5175 3.83..."
13,44,LA GUAJIRA,1964,Acto Legislativo No. 1 de Diciembre 28 de 1964,20620.239023,2024,10.792601,1.706976,"MULTIPOLYGON (((-72.48729 11.77722, -72.48717 ..."
14,47,MAGDALENA,1964,1964,23135.961102,2024,10.813490,1.909268,"MULTIPOLYGON (((-74.04165 11.34162, -74.04154 ..."
15,50,META,1959,Ley 118 del 16 de Diciembre de 1959,82830.185752,2024,18.192106,6.736155,"MULTIPOLYGON (((-71.07793 4.8991, -71.07791 4...."
16,52,NARIÑO,1904,Ley 1 de 1904,31497.033511,2024,12.839508,2.548431,"MULTIPOLYGON (((-78.88306 1.50993, -78.88276 1..."
17,54,NORTE DE SANTANDER,1910,Ley 25 de 1910,21887.814554,2024,10.879925,1.794874,"MULTIPOLYGON (((-73.00391 9.2802, -73.00496 9...."
18,63,QUINDIO,1966,Ley 2 TM de 1966,1933.570847,2024,2.554825,0.157424,"MULTIPOLYGON (((-75.70194 4.72049, -75.7018 4...."
19,66,RISARALDA,1966,Ley 70 del 1 de Diciembre de 1966,3556.750064,2024,4.851530,0.289789,"MULTIPOLYGON (((-76.00824 5.56366, -76.00765 5..."
20,68,SANTANDER,1910,Ley 25 14 de Julio de 1910,30561.565645,2024,11.876862,2.499110,"MULTIPOLYGON (((-73.77429 8.10825, -73.77413 8..."
21,70,SUCRE,1966,Ley 47 del 8 de Agosto de 1966,10591.872415,2024,8.558391,0.870813,"MULTIPOLYGON (((-75.5232 10.09167, -75.53704 1..."
22,73,TOLIMA,1909,Ley 65 de Noviembre de 1909,24139.432402,2024,9.550110,1.965029,"MULTIPOLYGON (((-74.62657 4.22285, -74.62637 4..."
23,76,VALLE DEL CAUCA,1910,Decreto No 340 de 16 de Abril de 1910,20665.583719,2024,12.656887,1.679490,"MULTIPOLYGON (((-77.2381 4.04049, -77.23774 4...."
24,81,ARAUCA,1991,5 de Julio Constitucion Politica de 1991,23851.257059,2024,9.124586,1.944157,"MULTIPOLYGON (((-70.68038 7.09393, -70.67987 7..."
25,85,CASANARE,1991,5 de Julio Constitucion Politica de 1991,44394.235851,2024,12.132763,3.615063,"MULTIPOLYGON (((-72.33885 6.34471, -72.3392 6...."
26,86,PUTUMAYO,1991,Articulo 309 Constitucion Politica de 1991,25976.283106,2024,12.707922,2.107965,"MULTIPOLYGON (((-76.6705 1.46732, -76.67 1.467..."
27,88,"ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANT...",1991,Artículo 310 Constitucion Politica de 1991,49.417693,2024,0.683356,0.004049,"MULTIPOLYGON (((-81.68843 12.54957, -81.68845 ..."
28,91,AMAZONAS,1991,Dcto. 2274 del 4 de Octubre de la Constitución...,109497.053786,2024,25.355977,8.877480,"MULTIPOLYGON (((-71.14469 0.05572, -71.14508 0..."
29,94,GUAINÍA,1991,Articulo 309 Constitucion Politica de 1991,71289.354683,2024,21.179051,5.747937,"MULTIPOLYGON (((-67.67638 3.91228, -67.67305 3..."
30,95,GUAVIARE,1991,5 de Julio Constitucion Politica de 1991,55543.867513,2024,19.394103,4.508908,"MULTIPOLYGON (((-71.31266 2.92463, -71.31215 2..."
31,97,VAUPÉS,1991,Articulo 309 Constitucion Politica de 1991,53299.280015,2024,20.129834,4.313810,"MULTIPOLYGON (((-70.11033 2.0801, -70.10981 2...."
32,99,VICHADA,1991,5 de Julio Constitucion Politica de 1991,100063.370593,2024,17.292613,8.100680,"MULTIPOLYGON (((-67.80972 6.32432, -67.80946 6..."

In [33]:
dataset.latitude.values

array([14.  , 13.75, 13.5 , 13.25, 13.  , 12.75, 12.5 , 12.25, 12.  ,
       11.75, 11.5 , 11.25, 11.  , 10.75, 10.5 , 10.25, 10.  ,  9.75,
        9.5 ,  9.25,  9.  ,  8.75,  8.5 ,  8.25,  8.  ,  7.75,  7.5 ,
        7.25,  7.  ,  6.75,  6.5 ,  6.25,  6.  ,  5.75,  5.5 ,  5.25,
        5.  ,  4.75,  4.5 ,  4.25,  4.  ,  3.75,  3.5 ,  3.25,  3.  ,
        2.75,  2.5 ,  2.25,  2.  ,  1.75,  1.5 ,  1.25,  1.  ,  0.75,
        0.5 ,  0.25,  0.  , -0.25, -0.5 , -0.75, -1.  , -1.25, -1.5 ,
       -1.75, -2.  , -2.25, -2.5 , -2.75, -3.  , -3.25, -3.5 , -3.75,
       -4.  , -4.25, -4.5 , -4.75, -5.  ])

In [32]:
import numpy as np

lat_grid , lon_grid = np.meshgrid(dataset.latitude.values, dataset.longitude.values, indexing='ij')
lat_indeces, lon_indeces = np.indices(lat_grid.shape)
lat_indeces

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 1,  1,  1, ...,  1,  1,  1],
       [ 2,  2,  2, ...,  2,  2,  2],
       ...,
       [74, 74, 74, ..., 74, 74, 74],
       [75, 75, 75, ..., 75, 75, 75],
       [76, 76, 76, ..., 76, 76, 76]], shape=(77, 69))

In [34]:
lat_grid

array([[14.  , 14.  , 14.  , ..., 14.  , 14.  , 14.  ],
       [13.75, 13.75, 13.75, ..., 13.75, 13.75, 13.75],
       [13.5 , 13.5 , 13.5 , ..., 13.5 , 13.5 , 13.5 ],
       ...,
       [-4.5 , -4.5 , -4.5 , ..., -4.5 , -4.5 , -4.5 ],
       [-4.75, -4.75, -4.75, ..., -4.75, -4.75, -4.75],
       [-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ]], shape=(77, 69))

In [23]:
grid_pts = gpd.GeoDataFrame({
    "lat_ind" : lat_indeces.ravel(),
    "lon_ind" : lon_indeces.ravel()
},
geometry=gpd.points_from_xy(lon_grid.ravel(), lat_grid.ravel()),
crs="EPSG:4326")
grid_pts

      lat_ind  lon_ind           geometry
0           0        0     POINT (-83 14)
1           0        1  POINT (-82.75 14)
2           0        2   POINT (-82.5 14)
3           0        3  POINT (-82.25 14)
4           0        4     POINT (-82 14)
...       ...      ...                ...
5308       76       64     POINT (-67 -5)
5309       76       65  POINT (-66.75 -5)
5310       76       66   POINT (-66.5 -5)
5311       76       67  POINT (-66.25 -5)
5312       76       68     POINT (-66 -5)

[5313 rows x 3 columns]

In [26]:
points_with_departments = gpd.sjoin(grid_pts, department_polygons[['dpto_ccdgo', 'dpto_cnmbr', 'geometry']], how='left', predicate='within')
points_with_departments

      lat_ind  lon_ind           geometry  index_right dpto_ccdgo dpto_cnmbr
0           0        0     POINT (-83 14)          NaN        NaN        NaN
1           0        1  POINT (-82.75 14)          NaN        NaN        NaN
2           0        2   POINT (-82.5 14)          NaN        NaN        NaN
3           0        3  POINT (-82.25 14)          NaN        NaN        NaN
4           0        4     POINT (-82 14)          NaN        NaN        NaN
...       ...      ...                ...          ...        ...        ...
5308       76       64     POINT (-67 -5)          NaN        NaN        NaN
5309       76       65  POINT (-66.75 -5)          NaN        NaN        NaN
5310       76       66   POINT (-66.5 -5)          NaN        NaN        NaN
5311       76       67  POINT (-66.25 -5)          NaN        NaN        NaN
5312       76       68     POINT (-66 -5)          NaN        NaN        NaN

[5313 rows x 6 columns]

In [35]:
points_with_departments = points_with_departments.dropna(subset='dpto_ccdgo')
points_with_departments

,lat_ind,lon_ind,geometry,index_right,dpto_ccdgo,dpto_cnmbr
528,7,45,POINT (-71.75 12.25),13.0,44,LA GUAJIRA
529,7,46,POINT (-71.5 12.25),13.0,44,LA GUAJIRA
530,7,47,POINT (-71.25 12.25),13.0,44,LA GUAJIRA
596,8,44,POINT (-72 12),13.0,44,LA GUAJIRA
597,8,45,POINT (-71.75 12),13.0,44,LA GUAJIRA
...,...,...,...,...,...,...
4882,70,52,POINT (-70 -3.5),28.0,91,AMAZONAS
4949,71,50,POINT (-70.5 -3.75),28.0,91,AMAZONAS
4950,71,51,POINT (-70.25 -3.75),28.0,91,AMAZONAS
4951,71,52,POINT (-70 -3.75),28.0,91,AMAZONAS
5020,72,52,POINT (-70 -4),28.0,91,AMAZONAS

In [36]:
points_with_departments.groupby(['dpto_ccdgo', 'dpto_cnmbr']).size().sort_values()

dpto_ccdgo  dpto_cnmbr
11          BOGOTÁ, D.C.            1
63          QUINDIO                 2
08          ATLÁNTICO               3
66          RISARALDA               6
17          CALDAS                  8
70          SUCRE                  13
41          HUILA                  24
76          VALLE DEL CAUCA        26
25          CUNDINAMARCA           27
44          LA GUAJIRA             29
54          NORTE DE SANTANDER     30
20          CESAR                  31
47          MAGDALENA              32
23          CÓRDOBA                32
81          ARAUCA                 33
73          TOLIMA                 33
86          PUTUMAYO               34
15          BOYACÁ                 34
13          BOLÍVAR                35
52          NARIÑO                 40
68          SANTANDER              40
19          CAUCA                  42
85          CASANARE               57
27          CHOCÓ                  61
97          VAUPÉS                 70
95          GUAVIARE               73
05          ANTIOQUIA              87
94          GUAINÍA                95
50          META                  107
18          CAQUETÁ               123
99          VICHADA               128
91          AMAZONAS              137
dtype: int64

In [ ]:
lat_i = xr.DataArray(points_with_departments['lat_ind'].to_numpy(dtype='int64'), dims='points')

lon_i = xr.DataArray(points_with_departments['lon_ind'].to_numpy(dtype='int64'), dims='points')

points_temp = dataset['t2m'].isel(latitude=lat_i, longitude=lon_i)

('time', 'points')

In [44]:
points_temp = points_temp.assign_coords(department=('points', points_with_departments['dpto_ccdgo'].astype(str).to_numpy()))
points_temp

<xarray.DataArray 't2m' (time: 87672, points: 1493)> Size: 524MB
dask.array<transpose, shape=(87672, 1493), dtype=float32, chunksize=(24, 1493), chunktype=numpy.ndarray>
Coordinates:
  * time        (time) datetime64[ns] 701kB 2016-01-01 ... 2025-12-31T23:00:00
    valid_time  (time) datetime64[ns] 701kB dask.array<chunksize=(24,), meta=np.ndarray>
    latitude    (points) float64 12kB 12.25 12.25 12.25 ... -3.75 -3.75 -4.0
    longitude   (points) float64 12kB -71.75 -71.5 -71.25 ... -70.25 -70.0 -70.0
    department  (points) object 12kB '44' '44' '44' '44' ... '91' '91' '91' '91'
    number      int64 8B ...
    step        timedelta64[ns] 8B ...
    surface     float64 8B ...
Dimensions without coordinates: points
Attributes: (12/31)
    GRIB_paramId:                             167
    GRIB_dataType:                            an
    GRIB_numberOfPoints:                      5313
    GRIB_typeOfLevel:                         surface
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    ...                                       ...
    GRIB_shortName:                           2t
    GRIB_totalNumber:                         0
    GRIB_units:                               K
    long_name:                                2 metre temperature
    units:                                    K
    standard_name:                            unknown

In [49]:
hourly_by_department = (points_temp - 273.15).groupby('department').mean('points').rename('2m_temperature')
hourly_by_department

<xarray.DataArray '2m_temperature' (time: 87672, department: 32)> Size: 11MB
dask.array<transpose, shape=(87672, 32), dtype=float32, chunksize=(24, 1), chunktype=numpy.ndarray>
Coordinates:
  * time        (time) datetime64[ns] 701kB 2016-01-01 ... 2025-12-31T23:00:00
    valid_time  (time) datetime64[ns] 701kB dask.array<chunksize=(24,), meta=np.ndarray>
  * department  (department) object 256B '05' '08' '11' '13' ... '95' '97' '99'
    number      int64 8B ...
    step        timedelta64[ns] 8B ...
    surface     float64 8B ...
Attributes: (12/31)
    GRIB_paramId:                             167
    GRIB_dataType:                            an
    GRIB_numberOfPoints:                      5313
    GRIB_typeOfLevel:                         surface
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    ...                                       ...
    GRIB_shortName:                           2t
    GRIB_totalNumber:                         0
    GRIB_units:                               K
    long_name:                                2 metre temperature
    units:                                    K
    standard_name:                            unknown