In [4]:
from dotenv import load_dotenv
import os
import boto3
import pandas as pd

load_dotenv()

s3 = boto3.client(
    "s3",
    endpoint_url=f"https://{os.environ['R2_ACCOUNT_ID']}.r2.cloudflarestorage.com",
    aws_access_key_id=os.environ["R2_ACCESS_KEY_ID"],
    aws_secret_access_key=os.environ["R2_SECRET_ACCESS_KEY"],
    region_name="auto",
)

bucket = "colombia-dengue-forecasting"

In [5]:
years = ["2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025"]

cases_data_frames = []

for year in years:
    key = f"raw/cases/Datos_{year}_210.xlsx"
    local_path = f"data/raw/cases/{year}.xlsx"

    s3.download_file(bucket, key, local_path)
    df = pd.read_excel(local_path)
    cases_data_frames.append(df)

In [6]:
cases_data_frames[0].info()

<class 'pandas.DataFrame'>
RangeIndex: 100117 entries, 0 to 100116
Data columns (total 69 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   CONSECUTIVE                100117 non-null  int64
 1   COD_EVE                    100117 non-null  int64
 2   FEC_NOT                    100117 non-null  str
 3   SEMANA                     100117 non-null  int64
 4   ANO                        100117 non-null  int64
 5   COD_PRE                    100117 non-null  int64
 6   COD_SUB                    100117 non-null  int64
 7   EDAD                       100117 non-null  int64
 8   UNI_MED                    100117 non-null  int64
 9   SEXO                       100117 non-null  str
 10  COD_PAIS_O                 100117 non-null  int64
 11  COD_DPTO_O                 100117 non-null  int64
 12  COD_MUN_O                  100117 non-null  int64
 13  AREA                       100117 non-null  int64
 14  OCUPACION                  100117 non-null  int64
 15  TIP_SS                     100117 non-null  str
 16  COD_ASE                    96216 non-null   str
 17  PER_ETN                    100117 non-null  int64
 18  GRU_POB                    0 non-null       float64
 19  nom_grupo                  0 non-null       float64
 20  estrato                    0 non-null       float64
 21  GP_DISCAPA                 100117 non-null  int64
 22  GP_DESPLAZ                 100117 non-null  int64
 23  GP_MIGRANT                 100117 non-null  int64
 24  GP_CARCELA                 100117 non-null  int64
 25  GP_GESTAN                  100117 non-null  int64
 26  sem_ges                    0 non-null       float64
 27  GP_INDIGEN                 100117 non-null  int64
 28  GP_POBICFB                 100117 non-null  int64
 29  GP_MAD_COM                 100117 non-null  int64
 30  GP_DESMOVI                 100117 non-null  int64
 31  GP_PSIQUIA                 100117 non-null  int64
 32  GP_VIC_VIO                 100117 non-null  int64
 33  GP_OTROS                   100117 non-null  int64
 34  fuente                     0 non-null       float64
 35  COD_PAIS_R                 0 non-null       float64
 36  COD_DPTO_R                 100117 non-null  int64
 37  COD_MUN_R                  100117 non-null  int64
 38  COD_DPTO_N                 100117 non-null  int64
 39  COD_MUN_N                  100117 non-null  int64
 40  FEC_CON                    100093 non-null  str
 41  INI_SIN                    100093 non-null  str
 42  TIP_CAS                    100117 non-null  int64
 43  PAC_HOS                    100117 non-null  int64
 44  FEC_HOS                    29484 non-null   str
 45  CON_FIN                    100117 non-null  int64
 46  FEC_DEF                    2 non-null       str
 47  AJUSTE                     100117 non-null  int64
 48  FECHA_NTO                  99828 non-null   str
 49  CBMTE                      3 non-null       str
 50  FEC_ARC_XL                 100117 non-null  str
 51  FEC_AJU                    100117 non-null  str
 52  FM_FUERZA                  803 non-null     float64
 53  FM_UNIDAD                  803 non-null     float64
 54  FM_GRADO                   803 non-null     str
 55  confirmados                100117 non-null  int64
 56  va_sispro                  100117 non-null  int64
 57  Estado_final_de_caso       100117 non-null  int64
 58  nom_est_f_caso             100117 non-null  str
 59  Nombre_upgd                100117 non-null  str
 60  Pais_ocurrencia            100117 non-null  str
 61  Nombre_evento              100117 non-null  str
 62  Departamento_ocurrencia    100117 non-null  str
 63  Municipio_ocurrencia       100117 non-null  str
 64  Pais_residencia            0 non-null       float64
 65  Departamento_residencia    100117 non-null  str
 66  Municipio_residencia       100117 non-null  str
 67  Departamento_Notificacion  100117 non-null  str
 68  Municipio_notificacion     100117 non-null  str
dtypes: float64(9), int64(37), str(23)
memory usage: 52.7 MB

| Column | Meaning | Values / format |
|---|---|---|
| `COD_EVE` | SIVIGILA event code | `210` = dengue; `220` = severe dengue; `580` = dengue mortality, handled as a separate event |
| `ANO` | Epidemiological year | The years present in the dataset |
| `SEMANA` | Epidemiological week | Week number, generally `1`–`53`; use the week paired with `ANO` |
| `COD_DPTO_O` | Department where the case occurred | DANE DIVIPOLA department code; keep as text to preserve leading zeros |
| `COD_MUN_O` | Municipality where the case occurred | DANE DIVIPOLA municipality code; check whether this export stores the municipality component or the full code |
| `COD_PAIS_O` | Country where the case occurred | Country code; Colombia is commonly represented as `170` |
| `INI_SIN` | Date symptoms began | Date; parse using the format in your source file |
| `FEC_NOT` | Date the case was notified | Date; parse using the format in your source file |
| `TIP_CAS` | Initial case classification/type | Event- and year-specific code; check the dengue data dictionary and the values in your files |
| `AJUSTE` | Case adjustment or updated classification | Dengue protocol mentions `3` = confirmed by laboratory, `5` = confirmed by epidemiological link, `6` = discarded, and `D` = digitization error; verify other values by year |
| `CONSECUTIVE` | Sequential record identifier | Identifier, not a category; uniqueness is not guaranteed across separate yearly files |

In [7]:
cols_to_keep = ["CONSECUTIVE", "COD_EVE", "ANO", "SEMANA", "COD_DPTO_O", "COD_MUN_O", "COD_PAIS_O", "INI_SIN", "FEC_NOT", "TIP_CAS", "AJUSTE"]
for i in range(0,len(cases_data_frames)):
    cases_data_frames[i] = cases_data_frames[i][cols_to_keep]

cases_data_frames[0].head()

,CONSECUTIVE,COD_EVE,ANO,SEMANA,COD_DPTO_O,COD_MUN_O,COD_PAIS_O,INI_SIN,FEC_NOT,TIP_CAS,AJUSTE
0,713315,210,2016,21,5,1,170,25/05/2016 12:00:00 a. m.,1/06/2016 12:00:00 a. m.,3,0
1,713316,210,2016,3,5,1,170,18/01/2016 12:00:00 a. m.,21/01/2016 12:00:00 a. m.,3,0
2,713323,210,2016,2,5,1,170,15/01/2016 12:00:00 a. m.,23/01/2016 12:00:00 a. m.,2,0
3,713353,210,2016,22,5,1,170,1/06/2016 12:00:00 a. m.,11/06/2016 12:00:00 a. m.,3,0
4,713310,210,2016,25,5,1,170,20/06/2016 12:00:00 a. m.,25/06/2016 12:00:00 a. m.,2,0

| Column | Value | Meaning |
|---|---:|---|
| `TIP_CAS` | `2` | Probable case |
| `TIP_CAS` | `3` | Confirmed by laboratory |
| `TIP_CAS` | `5` | Confirmed by epidemiological link |
| `AJUSTE` | `0` | No adjustment / first report |
| `AJUSTE` | `3` | Adjustment confirming by laboratory |
| `AJUSTE` | `5` | Adjustment confirming by epidemiological link |
| `AJUSTE` | `7` | Other update to the record; not a case classification |

In [8]:
global_cases = pd.concat(cases_data_frames, axis=0, join='outer', ignore_index=True)

In [9]:
# Only cases that ocurred in Colombia, identified with M49 code 170 1037761
global_cases = global_cases[global_cases['COD_PAIS_O'] == 170]
global_cases

,CONSECUTIVE,COD_EVE,ANO,SEMANA,COD_DPTO_O,COD_MUN_O,COD_PAIS_O,INI_SIN,FEC_NOT,TIP_CAS,AJUSTE
0,713315,210,2016,21,5,1,170,25/05/2016 12:00:00 a. m.,1/06/2016 12:00:00 a. m.,3,0
1,713316,210,2016,3,5,1,170,18/01/2016 12:00:00 a. m.,21/01/2016 12:00:00 a. m.,3,0
2,713323,210,2016,2,5,1,170,15/01/2016 12:00:00 a. m.,23/01/2016 12:00:00 a. m.,2,0
3,713353,210,2016,22,5,1,170,1/06/2016 12:00:00 a. m.,11/06/2016 12:00:00 a. m.,3,0
4,713310,210,2016,25,5,1,170,20/06/2016 12:00:00 a. m.,25/06/2016 12:00:00 a. m.,2,0
...,...,...,...,...,...,...,...,...,...,...,...
1040490,4754,210,2025,51,68,689,170,18/12/2025 12:00:00 a. m.,19/12/2025 12:00:00 a. m.,3,0
1040491,4716,210,2025,3,8,758,170,12/01/2025 12:00:00 a. m.,17/01/2025 12:00:00 a. m.,3,3
1040492,4655,210,2025,50,47,1,170,8/12/2025 12:00:00 a. m.,12/12/2025 12:00:00 a. m.,3,0
1040493,1974,210,2025,28,73,1,170,10/07/2025 12:00:00 a. m.,14/07/2025 12:00:00 a. m.,2,7
1040494,4757,210,2025,40,47,1,170,29/09/2025 12:00:00 a. m.,4/10/2025 12:00:00 a. m.,3,3

In [10]:
for col in cols_to_keep:
    print(col)
    print(global_cases[col].isnull().sum())

CONSECUTIVE
0
COD_EVE
0
ANO
0
SEMANA
0
COD_DPTO_O
0
COD_MUN_O
0
COD_PAIS_O
0
INI_SIN
24
FEC_NOT
0
TIP_CAS
0
AJUSTE
0

| Código | Departamento | Código | Departamento |
|---:|---|---:|---|
| 05 | Antioquia | 52 | Nariño |
| 08 | Atlántico | 54 | Norte de Santander |
| 11 | Bogotá, D.C. | 63 | Quindío |
| 13 | Bolívar | 66 | Risaralda |
| 15 | Boyacá | 68 | Santander |
| 17 | Caldas | 70 | Sucre |
| 18 | Caquetá | 73 | Tolima |
| 19 | Cauca | 76 | Valle del Cauca |
| 20 | Cesar | 81 | Arauca |
| 23 | Córdoba | 85 | Casanare |
| 25 | Cundinamarca | 86 | Putumayo |
| 27 | Chocó | 88 | San Andrés y Providencia |
| 41 | Huila | 91 | Amazonas |
| 44 | La Guajira | 94 | Guainía |
| 47 | Magdalena | 95 | Guaviare |
| 50 | Meta | 97 | Vaupés |
|  |  | 99 | Vichada |

In [18]:
department_codes = global_cases["COD_DPTO_O"].value_counts().index.tolist()
department_codes_df = pd.DataFrame(data=department_codes, columns=['COD_DPTO_O'])
department_codes_df = department_codes_df[department_codes_df['COD_DPTO_O'] != 0]
department_codes_df

    COD_DPTO_O
0           76
1           68
2           73
3            5
4           50
5           13
6           41
7            8
8           54
9           23
10          25
11          20
12          70
13          85
14          47
15          19
16          86
17          44
18          66
19          63
20          18
21          81
22          52
23          27
24          15
25          17
26          91
27          95
28          99
29          88
30          94
31          97

In [19]:
global_cases = global_cases[global_cases["COD_DPTO_O"] != 0]
global_cases.shape[0]

1037727

In [20]:
keys = ['ANO', 'SEMANA', 'COD_DPTO_O']
counts_by_week_year_department = global_cases.groupby(keys).size().rename('case_count').reset_index()
counts_by_week_year_department

        ANO  SEMANA  COD_DPTO_O  case_count
0      2016       1           5         391
1      2016       1           8         128
2      2016       1          13          69
3      2016       1          15          21
4      2016       1          17          25
...     ...     ...         ...         ...
15400  2025      53          85           6
15401  2025      53          86           9
15402  2025      53          91          12
15403  2025      53          95           4
15404  2025      53          99           3

[15405 rows x 4 columns]

In [21]:

import numpy as np

epidemological_weeks_per_year = [(2016, 52),(2017, 52),(2018, 52),(2019, 52),(2020, 53),(2021, 52),(2022, 52),(2023, 52),(2024, 52),(2025, 53)]

year_week = np.array([(year , week) for year, num_weeks in epidemological_weeks_per_year for week in range(1, num_weeks + 1)])
year_week_df = pd.DataFrame(data = year_week, columns=['ANO', 'SEMANA'])
year_week_df

      ANO  SEMANA
0    2016       1
1    2016       2
2    2016       3
3    2016       4
4    2016       5
..    ...     ...
517  2025      49
518  2025      50
519  2025      51
520  2025      52
521  2025      53

[522 rows x 2 columns]

In [22]:
department_year_week_df = year_week_df.merge(department_codes_df, how='cross')
department_year_week_df

        ANO  SEMANA  COD_DPTO_O
0      2016       1          76
1      2016       1          68
2      2016       1          73
3      2016       1           5
4      2016       1          50
...     ...     ...         ...
16699  2025      53          95
16700  2025      53          99
16701  2025      53          88
16702  2025      53          94
16703  2025      53          97

[16704 rows x 3 columns]

In [28]:
weekly_cases_complete_df = department_year_week_df.merge(counts_by_week_year_department, on=keys, how='left').fillna({'case_count' : 0})
weekly_cases_complete_df['case_count'] = weekly_cases_complete_df['case_count'].astype(int)
weekly_cases_complete_df

        ANO  SEMANA  COD_DPTO_O  case_count
0      2016       1          76         558
1      2016       1          68         148
2      2016       1          73         269
3      2016       1           5         391
4      2016       1          50          57
...     ...     ...         ...         ...
16699  2025      53          95           4
16700  2025      53          99           3
16701  2025      53          88           0
16702  2025      53          94           0
16703  2025      53          97           0

[16704 rows x 4 columns]

In [29]:
print(weekly_cases_complete_df['COD_DPTO_O'].unique())

[76 68 73  5 50 13 41  8 54 23 25 20 70 85 47 19 86 44 66 63 18 81 52 27
 15 17 91 95 99 88 94 97]